# Remove regenerated build/run artifacts. Does NOT touch source: Content\, cache\,
# src, or any .ps1 launcher scripts. Also keeps data\pack (the generated script
# bundle) so the server can boot without re-running the JDK/Gradle compile - delete
# it manually if you want to force a clean recompile.
#
# Usage:
#   .\clean.ps1                 # cargo clean + wasm bundle + temp cache + root logs
#   .\clean.ps1 -KeepTarget     # keep the cargo target\ dir (skip the slow rebuild)
#   .\clean.ps1 -Screens        # also delete root debug screenshots (*.png, *.jpg)
param(
    [switch]$KeepTarget,
    [switch]$Screens
)
$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

function Remove-IfPresent($path, $label) {
    if (Test-Path $path) {
        Write-Host "  - removing $label" -ForegroundColor DarkYellow
        Remove-Item -Recurse -Force $path
    }
}

Write-Host "==> cleaning regenerated artifacts (Content\, cache\, data\ are preserved)" -ForegroundColor Cyan

# Cargo build output (regenerated by cargo build).
if ($KeepTarget) {
    Write-Host "  - keeping target\ (-KeepTarget)" -ForegroundColor DarkGray
} else {
    Write-Host "  - cargo clean (target\)" -ForegroundColor DarkYellow
    cargo clean
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
}

# wasm-bindgen bundle (regenerated by run-client-wasm.ps1 / crates\client\web\build.ps1).
Remove-IfPresent (Join-Path $PSScriptRoot "crates\client\web\pkg") "wasm bundle (crates\client\web\pkg)"

# Server's temp Content->cache pack (regenerated on every server boot).
Remove-IfPresent (Join-Path $env:TEMP "os_content_cache") "temp content cache (`$TEMP\os_content_cache)"

# Root run logs (panel_run.log, client_*.log, *.err.log, *.out.log, ...).
$logs = Get-ChildItem -Path $PSScriptRoot -Filter *.log -File -ErrorAction SilentlyContinue
if ($logs) {
    Write-Host "  - removing $($logs.Count) root log file(s)" -ForegroundColor DarkYellow
    $logs | Remove-Item -Force
}

# Optional: debug screenshots at the repo root (one-off captures, gitignored).
if ($Screens) {
    $imgs = Get-ChildItem -Path (Join-Path $PSScriptRoot "*") -Include *.png, *.jpg -File -ErrorAction SilentlyContinue
    if ($imgs) {
        Write-Host "  - removing $($imgs.Count) root screenshot(s) (-Screens)" -ForegroundColor DarkYellow
        $imgs | Remove-Item -Force
    }
}

Write-Host "==> done." -ForegroundColor Green
