# Remove regenerated build/run artifacts. Does NOT touch source: Content\, cache\,
# src, or any .ps1 launcher scripts.
#
# Removes: cargo target\, the wasm bundle, the server's temp content cache, root
# logs, the root Gradle build\ dir, target_audit\, and the generated data\pack
# script bundle (recompiled from Content\scripts on the next server boot - needs JDK 21).
#
# Usage:
#   .\clean.ps1                 # full clean
#   .\clean.ps1 -KeepTarget     # keep the cargo target\ dir (skip the slow rebuild)
#   .\clean.ps1 -Screens        # also delete root debug screenshots (*.png, *.jpg)
param(
    [switch]$KeepTarget,
    [switch]$Screens
)
$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

function Remove-IfPresent($path, $label) {
    if (Test-Path $path) {
        Write-Host "  - removing $label" -ForegroundColor DarkYellow
        Remove-Item -Recurse -Force $path
    }
}

Write-Host "==> cleaning regenerated artifacts (Content\ and cache\ are preserved)" -ForegroundColor Cyan

# Cargo build output (regenerated by cargo build).
if ($KeepTarget) {
    Write-Host "  - keeping target\ (-KeepTarget)" -ForegroundColor DarkGray
} else {
    Write-Host "  - cargo clean (target\)" -ForegroundColor DarkYellow
    cargo clean
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
}

# wasm-bindgen bundle (regenerated by run-client-wasm.ps1 / crates\client\web\build.ps1).
Remove-IfPresent (Join-Path $PSScriptRoot "crates\client\web\pkg") "wasm bundle (crates\client\web\pkg)"

# Server's temp Content->cache pack (regenerated on every server boot).
Remove-IfPresent (Join-Path $env:TEMP "os_content_cache") "temp content cache (`$TEMP\os_content_cache)"

# Gradle build output (root Java client + IntelliJ plugin) and the stale audit target.
Remove-IfPresent (Join-Path $PSScriptRoot "build") "Gradle build output (build\)"
Remove-IfPresent (Join-Path $PSScriptRoot "target_audit") "stale audit target (target_audit\)"

# Generated RuneScript bundle (recompiled from Content\scripts on the next server
# boot when JDK 21 is present).
Remove-IfPresent (Join-Path $PSScriptRoot "data\pack") "generated script bundle (data\pack)"

# Root run logs (panel_run.log, client_*.log, *.err.log, *.out.log, ...).
$logs = Get-ChildItem -Path $PSScriptRoot -Filter *.log -File -ErrorAction SilentlyContinue
if ($logs) {
    Write-Host "  - removing $($logs.Count) root log file(s)" -ForegroundColor DarkYellow
    $logs | Remove-Item -Force
}

# Optional: debug screenshots at the repo root (one-off captures, gitignored).
if ($Screens) {
    $imgs = Get-ChildItem -Path (Join-Path $PSScriptRoot "*") -Include *.png, *.jpg -File -ErrorAction SilentlyContinue
    if ($imgs) {
        Write-Host "  - removing $($imgs.Count) root screenshot(s) (-Screens)" -ForegroundColor DarkYellow
        $imgs | Remove-Item -Force
    }
}

Write-Host "==> done." -ForegroundColor Green
